apiVersion: apps/v1
kind: Deployment
metadata:
  name: gened-fe-learner-deployment
  namespace: gened-fe-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gened-fe-learner
  template:
    metadata:
      labels:
        app: gened-fe-learner
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: gened-fe-learner-container
          image: ghcr.io/fcodemonday/poc-action:latest
          containerPort: 3000
