apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gened-fe-learner-ingress
  namespace: gened-fe-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: gened-fe-dev.codemonday.io
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: gened-fe-learner-service
                port:
                  number: 80
          - path: /_next/*
            pathType: Prefix
            backend:
              service:
                name: gened-fe-learner-service
                port:
                  number: 80
