apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gened-fe-learner-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx   # <-- Make sure this matches your Ingress Controller
  rules:
    - host: gened-fe-dev.codemonday.io
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gened-fe-learner-service
                port:
                  number: 80