apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZmNvZGVtb25kYXkiLCJwYXNzd29yZCI6ImdpdGh1Yl9wYXRfMTFCSlNTWFdBMG9HbUk0ZjJJVTFxV19xRHVIMnZaaUZyTTFzeDA2WFdMM1dzSk1XakNDUkJuMjNOdEYwWVNFR2FuWU83TEpWN1dJbjBscEpZayIsImVtYWlsIjoicGljaGFpLmtAY29kZW1vbmRheS5jb20iLCJhdXRoIjoiWm1OdlpHVnRiMjVrWVhrNloybDBhSFZpWDNCaGRGOHhNVUpLVTFOWVYwRXdiMGR0U1RSbU1rbFZNWEZYWDNGRWRVZ3lkbHBwUm5KTk1YTjRNRFpZVjB3elYzTktUVmRxUTBOU1FtNHlNMDUwUmpCWlUwVkhZVzVaVHpkTVNsWTNWMGx1TUd4d1NsbHIifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: gened-fe-learner
type: kubernetes.io/dockerconfigjson
