apiVersion: v1
kind: Service
metadata:
  name: gened-fe-learner-service
  namespace: gened-fe-dev
spec:
  selector:
    app: gened-fe-learner
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 80
      protocol: TCP